### ISSUE TITLE
NoClassDefFoundError:sun/awt/SunToolkit$InfiniteLoop after upgrade java to 8u301

### ISSUE THREAD

**Issue by Bellama1** [robotframework/remoteswinglibrary#102]
Hi,
   After upgrade to java 8u301, a error occurs when call keyword  "Set Jemmy Timeouts". The error message is :java.lang.ClassNotFoundException: sun.awt.SunToolkit$InfiniteLoop. Please help check the issue
