### ISSUE TITLE
remoteSwing Not working with robotframework v2.8.6

### ISSUE THREAD

**Issue by cyrilMargaria** [robotframework/remoteswinglibrary#2]
v1.1.1 throws the following error:

AttributeError: Namespace instance has no attribute '_testlibs'

Reason: 
RemoteSwingLibrary.py, RobotLibraryImporter does reference  EXECUTION_CONTEXTS.current.namespace._testlibs, wich disappeared in 

https://github.com/robotframework/robotframework/commit/6bb18a81bdf80b7ed87ebe4a3e2543e4a0967d1c#diff-b60e77935297ce1664a0df192568ed01
